# Generated by Django 4.0.6 on 2022-07-06 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('UID', models.UUIDField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(default='', max_length=1024)),
                ('primary_class', models.CharField(default='unknown', max_length=128)),
                ('secondary_class', models.CharField(default='unknown', max_length=128)),
                ('color_style', models.CharField(default='unknown', max_length=32)),
                ('price', models.FloatField(default=0)),
                ('sold_state', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
