# Generated by Django 4.0.6 on 2022-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
