# Generated by Django 4.0.4 on 2022-07-04 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('primary_class', models.CharField(default='unknown', max_length=128)),
                ('secondary_class', models.CharField(default='unknown', max_length=128)),
                ('color_style', models.CharField(default='unknown', max_length=32)),
                ('price', models.IntegerField(default=0)),
                ('sold_state', models.BooleanField(default=False)),
                ('media_folder', models.CharField(max_length=128)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
