# Generated by Django 4.0.4 on 2022-07-04 13:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0002_alter_productinfo_price_searchingrecords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='UID',
            field=models.UUIDField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='SearchingRecords',
        ),
    ]
