# Generated by Django 4.0.4 on 2022-07-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_remove_productinfo_id_productinfo_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinfo',
            name='media_folder',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='description',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
