# Generated by Django 4.0.4 on 2022-06-02 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128, unique=True)),
                ('encrypted_passwd', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(default='unknown', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField()),
            ],
            options={
                'db_table': 'userdb',
                'ordering': ['create_time'],
            },
        ),
    ]
