# Generated by Django 4.0.6 on 2022-07-26 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browser', '0002_alter_productinfo_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('out_trade_no', models.UUIDField(auto_created=True, default=uuid.uuid1, primary_key=True, serialize=False)),
                ('done', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_trade', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_trade', to='browser.productinfo')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
